Add RTP VP9 Reader Test
androidx/media pull request #114
Opened 2022-07-08 11:46 UTC by ManishaJajoo

Change-Id: Idcc6dcb62172b71465c30d8396b8a20533cc47b6

2022-07-11 13:03 UTC, claincly requested changes
Some refactoring comments. Please refer to the `RtpAmrReaderTest` for the style that we prefer, thanks!

2022-07-11 15:30 UTC, claincly commented on libraries/exoplayer_rtsp/src/test/java/androidx/media3/exoplayer/rtsp/reader/RtpVp9ReaderTest.java
> +  private final RtpPacket frame1fragment1 =
My bad, the names should be `FRAME_1_FRAGMENT_1`, and please make these fields `static final` too, thanks!

2022-07-12 18:41 UTC, claincly commented
NVM, I'll merge this one with #115 and change the styles.

2022-07-12 18:41 UTC, closed without merging

2022-07-13 02:29 UTC, ManishaJajoo commented
@claincly , apologies for the delay, the changes were in internal review. We have added the changes in our branch. You can take a look here: https://github.com/ittiam-systems/media/commit/a7adf755dd1a25765a19d6a71e08f8a418cb76ed

2022-07-13 13:57 UTC, claincly commented
No worries, thanks for making the change.