Update MediaPipe developer documentation links
androidx/media pull request #1548
Opened 2024-07-15 09:14 UTC by kikoso

The following PR fixes some broken links and updates the doc (documentation moved to  https://developers.google.com/mediapipe as the primary developer documentation site for MediaPipe as of April 3, 2023)

2024-07-17 16:35 UTC, calren requested changes
thanks for fixing the broken links!

2024-07-17 16:35 UTC, calren commented on demos/transformer/README.md
> +[MediaPipe]: https://developers.google.com/mediapipe
Can we update this to https://ai.google.dev/edge/mediapipe/solutions/guide?

This link is already redirecting there

2024-07-18 17:11 UTC, calren commented
LGTM

(although I don't have permission to approve PRs on this repo, so @droid-girl will have to officially approve this)

2024-07-18 17:12 UTC, calren approved these changes

2024-07-18 17:24 UTC, calren commented
Also, can you update the commit message to be more specific? Maybe something like: "Update MediaPipe developer documentation links"

2024-07-18 21:01 UTC, calren commented
yeah, updating the PR title should be fine. thanks for that!

2024-07-22 10:51 UTC, droid-girl approved these changes

2024-07-29 10:36 UTC, merged